CREATE TABLE `app_job` (
  `APP_JOB_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '表主键',
  `JOB_NAME` varchar(255) NOT NULL COMMENT 'JOB名称',
  `JOB_GROUP` varchar(255) NOT NULL COMMENT 'JOB所属组',
  `URI` varchar(255) NOT NULL COMMENT '请求地址',
  `NOTICE_ERROR_URI` varchar(255) DEFAULT NULL,
  `NEED_LOG` char(1) DEFAULT NULL,
  `DESCRIPTION` varchar(5000) DEFAULT NULL COMMENT '描述',
  `MAP_DATA` varchar(255) NOT NULL COMMENT 'KEY-VALUE键值对',
  `TRIGGER_TYPE` enum('CRON','SIMPLE') NOT NULL COMMENT '触发器类型',
  `REQUEST_WAY` enum('POST','GET') NOT NULL COMMENT '请求方式',
  `STATUS` enum('OPEN','COMPLETED','PASUSE') NOT NULL COMMENT '状态',
  `CRON` varchar(255) DEFAULT NULL COMMENT 'cron表达式',
  `REPEAT_COUNT` int(11) DEFAULT NULL COMMENT '执行记录',
  `REPEAT_INTERVAL` int(11) DEFAULT NULL COMMENT '间隔时间，单位毫秒',
  `START_TIME` datetime DEFAULT NULL COMMENT '任务开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '任务结束时间',
  `REASON` varchar(255) DEFAULT NULL COMMENT '注释处理原因',
  `INPUT_USER` varchar(255) DEFAULT NULL COMMENT '创建者',
  `UPDATE_USER` varchar(255) DEFAULT NULL COMMENT '修改者',
  `INPUT_DATE` datetime NOT NULL COMMENT '记录创建时间',
  `UPDATE_DATE` datetime NOT NULL COMMENT '记录修改时间',
  `UPDATE_VERSION` int(11) NOT NULL COMMENT '记录修改版本号',
  `IS_DELETE` char(255) NOT NULL DEFAULT 'N' COMMENT '是否逻辑删除',
  PRIMARY KEY (`APP_JOB_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;



CREATE TABLE `app_job_view` (
  `APP_JOB_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '表主键',
  `JOB_NAME` varchar(255) NOT NULL COMMENT 'JOB名称',
  `JOB_GROUP` varchar(255) NOT NULL COMMENT 'JOB所属组',
  `URI` varchar(255) NOT NULL COMMENT '请求地址',
  `DECPRTION` varchar(5000) NOT NULL COMMENT '描述',
  `MAP_DATA` varchar(255) NOT NULL COMMENT 'KEY-VALUE键值对',
  `TRIGGER_TYPE` enum('CRON','SIMPLE') NOT NULL COMMENT '触发器类型',
  `REQUEST_WAY` enum('POST','GET') NOT NULL COMMENT '请求方式',
  `STATUS` enum('STOP','OPEN') NOT NULL COMMENT '状态',
  `CRON` varchar(255) DEFAULT NULL COMMENT 'cron表达式',
  `REPEAT_COUNT` int(11) DEFAULT NULL,
  `REPEAT_INTERVAL` int(11) DEFAULT NULL,
  `PREV_FIRE_TIME` varchar(255) DEFAULT NULL,
  `NEXT_FIRE_TIME` varchar(255) DEFAULT NULL,
  `START_TIME` datetime DEFAULT NULL COMMENT '任务开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '任务结束时间',
  `REASON` varchar(255) DEFAULT NULL COMMENT '注释处理原因',
  `INPUT_USER` varchar(255) DEFAULT NULL COMMENT '创建者',
  `UPDATE_USER` varchar(255) DEFAULT NULL COMMENT '修改者',
  `INPUT_DATE` datetime NOT NULL COMMENT '记录创建时间',
  `UPDATE_DATE` datetime NOT NULL COMMENT '记录修改时间',
  `UPDATE_VERSION` int(11) NOT NULL COMMENT '记录修改版本号',
  `IS_DELETE` char(255) NOT NULL DEFAULT 'N' COMMENT '是否逻辑删除',
  PRIMARY KEY (`APP_JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `member` (
  `MEMBER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `MEMBER_NAME` varchar(255) NOT NULL COMMENT '会员名称',
  `ROLE` enum('ADMIN','MEMBER') NOT NULL COMMENT '角色',
  `PASS_WORD` varchar(255) NOT NULL COMMENT '密码',
  `REASON` varchar(255) DEFAULT NULL COMMENT '处理原因',
  `INPUT_DATE` datetime NOT NULL COMMENT '记录创建时间',
  `UPDATE_DATE` datetime NOT NULL COMMENT '记录修改时间',
  `UPDATE_VERSION` int(11) NOT NULL COMMENT '记录修改版本号',
  `IS_DELETE` char(255) NOT NULL DEFAULT 'N' COMMENT '是否逻辑删除',
  PRIMARY KEY (`MEMBER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

CREATE TABLE `member_group` (
  `MEMBER_GROUP_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `JOB_GROUP` varchar(255) DEFAULT NULL COMMENT '分组名称',
  `MEMBER_ID` int(11) DEFAULT NULL COMMENT '会员ID',
  `MEMBER_NAME` varchar(255) NOT NULL COMMENT '会员名称',
  `REASON` varchar(255) DEFAULT NULL COMMENT '注释处理原因',
  `INPUT_USER` varchar(255) NOT NULL COMMENT '创建者',
  `UPDATE_USER` varchar(255) NOT NULL COMMENT '修改者',
  `INPUT_DATE` datetime NOT NULL COMMENT '记录创建时间',
  `UPDATE_DATE` datetime NOT NULL COMMENT '记录修改时间',
  `UPDATE_VERSION` int(11) NOT NULL COMMENT '记录修改版本号',
  `IS_DELETE` char(255) NOT NULL DEFAULT 'N' COMMENT '是否逻辑删除',
  PRIMARY KEY (`MEMBER_GROUP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='记录成员与quartz的分组信息映射';

CREATE TABLE `result_history` (
  `RESULT_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `JOB_ID` int(11) NOT NULL COMMENT '任务ID，见APP_JOB表主键',
  `JOB_NAME` varchar(255) DEFAULT NULL,
  `JOB_GROUP` varchar(255) DEFAULT NULL,
  `BODY` varchar(5000) DEFAULT NULL COMMENT '报文',
  `SUCCESS` char(10) NOT NULL COMMENT '成功失败标记',
  `INPUT_DATE` datetime NOT NULL COMMENT '记录创建时间',
  `IS_DELETE` char(255) NOT NULL DEFAULT 'N' COMMENT '是否逻辑删除',
  PRIMARY KEY (`RESULT_HISTORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8 COMMENT='本表只用于查询和插入，来查询处理结果';







